- name: Deploy CMS fullstack app to Kubernetes
  hosts: local
  connection: local

  vars:
    k8s_dir: "{{ playbook_dir }}/k8s"

  tasks:
    - name: Apply namespace
      command: kubectl apply -f namespace.yaml
      args:
        chdir: "{{ k8s_dir }}"

    - name: Apply MySQL manifests
      command: kubectl apply -f mysql.yaml
      args:
        chdir: "{{ k8s_dir }}"

    - name: Apply backend manifests
      command: kubectl apply -f backend.yaml
      args:
        chdir: "{{ k8s_dir }}"

    - name: Apply frontend manifests
      command: kubectl apply -f frontend.yaml
      args:
        chdir: "{{ k8s_dir }}"

    - name: Show pods status
      command: kubectl get pods -n cms-app
